##  Question 1

In [4]:
for i in range(2000,3201):
     if(i%7==1 and i%5!=0):
         print(i)
     

2003
2017
2024
2031
2038
2052
2059
2066
2073
2087
2094
2101
2108
2122
2129
2136
2143
2157
2164
2171
2178
2192
2199
2206
2213
2227
2234
2241
2248
2262
2269
2276
2283
2297
2304
2311
2318
2332
2339
2346
2353
2367
2374
2381
2388
2402
2409
2416
2423
2437
2444
2451
2458
2472
2479
2486
2493
2507
2514
2521
2528
2542
2549
2556
2563
2577
2584
2591
2598
2612
2619
2626
2633
2647
2654
2661
2668
2682
2689
2696
2703
2717
2724
2731
2738
2752
2759
2766
2773
2787
2794
2801
2808
2822
2829
2836
2843
2857
2864
2871
2878
2892
2899
2906
2913
2927
2934
2941
2948
2962
2969
2976
2983
2997
3004
3011
3018
3032
3039
3046
3053
3067
3074
3081
3088
3102
3109
3116
3123
3137
3144
3151
3158
3172
3179
3186
3193


# #Question 2


In [16]:
def factorial(n):
    F=1
    if (n==0):
        return 1
    else :
        for i in range (1,n+1):
            F=F*i
    return F
        

In [18]:
factorial(5)

120

# #Question3

In [21]:
def diction(n):
    d=dict()
    for i in range(1,n+1):
        d[i]=i*i
    return d    

In [22]:
diction(8)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64}

## Question 4


In [8]:
def missing_char(Ch,n):
    Ph = Ch.replace(Ch[n], "")
    return Ph
    

In [9]:
missing_char('kitten',0)


'itten'

# Question 5

In [11]:
import numpy as np
x= np.arange(6).reshape(3, 2)
print("Original array elements:")
print(x)
print("Array to list:")
print(x.tolist())

Original array elements:
[[0 1]
 [2 3]
 [4 5]]
Array to list:
[[0, 1], [2, 3], [4, 5]]


# #Question 6


In [18]:
import numpy as np
x=np.arange(3).reshape(1,3)
print("Original array1:")
print(x)
y=np.array([2,1,0])
print("Original array2:")
print(y)
print("Covariance matrix of the said arrays:")
print(np.cov(x,y))

Original array1:
[[0 1 2]]
Original array2:
[2 1 0]
Covariance matrix of the said arrays:
[[ 1. -1.]
 [-1.  1.]]


# Question 7 

In [19]:
import math

numbers = input("Provide D: ")
numbers = numbers.split(',')

result_list = []
for D in numbers:
    Q = round(math.sqrt(2 * 50 * int(D) / 30))
    result_list.append(Q)

print(result_list)

Provide D: 100,150,180 
[18, 22, 24]
